name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: write  # Changed from 'read' to 'write' for creating tags
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          fetch-depth: 0  # Need full history for version determination
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Set up Git identity for potential commits
      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      # Auto-increment version based on commit messages
      - name: Auto versioning
        id: versioning
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          node scripts/auto-version.js
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "New version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      # Push version changes back to the repository
      - name: Push version changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.VERSION != ''
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected, pushing version updates"
            git add package.json src/app/services/version.service.ts
            git commit -m "chore: update version to $VERSION [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

      # Install OIDC client
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      
      # Build and deploy
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FOREST_088A4E70F }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/shadow-boxing/browser" # Updated output location to match the new app name
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######
      
      # Create tag for the new version
      - name: Create Git Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && env.VERSION != ''
        run: |
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin v${{ env.VERSION }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
